### PR TITLE
0.1.9 Release

### PR DESCRIPTION
**Pull request by below**
Updated the version number to 0.1.9

### CODE REVIEW

**Comment by valpinkman** [comment]
We need this <3

**Comment by DomiR** [comment]
Ping @mikolak

**Review by mikolak — APPROVED** [review]
Sorry, folks, but I'm not an active maintainer anymore. The change seems harmless, so I'll approve and merge, but any releases are not up to me.

**Comment by maccuaa** [comment]
@mikolak who is the active maintainer?

**Comment by below** [comment]
> @mikolak who is the active maintainer?

@OfftheCode , are you? https://github.com/dotintent/MultiPlatformBleAdapter/pull/81

**Comment by mikolak** [comment]
Someone from dotintent, I don't know. As you can see the library is no longer in Polidea space and I don't have enough free time to maintain 4 libraries (multiplatform ble adapter, Flutter BLE Lib, react-native-ble-plx, flutter blemulator), which is required for this BLE stack.

**Comment by chocky335** [comment]
@mobily @dusker @mrjenkins-ifm @OfftheCode please deploy new version, as now all libraries are broken on XCode 13

**Comment by srgtuszy** [comment]
New version will be deployed later today

**Comment by dbarati-bf** [comment]
> New version will be deployed later today

Are you talking about the react-native-ble-plx npm package? I haven't seen a release yet. Any estimates on when the fix will be released?

**Comment by rjgpereira** [comment]
Hi! Can this version be published in CocoaPods, please? 
Otherwise, people using FlutterBleLib won't benefit from this update.

**Comment by johnboiles** [comment]
Any volunteers for running a fork?

**Pull request merged**
