### PR TITLE
Fix for the iOS15 CoreBluetooth changes

### PR DESCRIPTION
**Pull request by below**
Some properties in CoreBluetooth have changed to optional. This changes addresses that issue.

Also, some warnings were removed

### CODE REVIEW

**Comment by bostnis** [comment]
I believe it needs to be merged quickly. Current version is not compiling in ios 15 (beta also)

**Comment by acasademont** [comment]
Yes lease, we would appreciate a merge soon. We're starting to test with Xcode 13/iOS 15 Betas and we can't compile right now. Can we help in any way? Thx!!

**Comment by georgeburduhos** [comment]
Anyone found a workaround before this will be merged?

**Comment by below** [comment]
> Anyone found a workaround before this will be merged?

We will use my branch as a workaround, using `npx patch-package` on  react-native-ble-plx

**Comment by georgeburduhos** [comment]
> > Anyone found a workaround before this will be merged?
> 
> We will use my branch as a workaround, using `npx patch-package` on react-native-ble-plx

Never used `npx patch-package` - can you help me a little bit?  Thanks in advance

**Comment by below** [comment]
@georgeburduhos I will post full instructions once I get it working

**Comment by georgeburduhos** [comment]
> @georgeburduhos I will post full instructions once I get it working

Super. thanks a lot. cause ios 15 is on us :)

**Comment by georgeburduhos** [comment]
Since its merged now i guess we need to wait the releases to be made?

**Comment by Vaneste** [comment]
@below Any chance to get the release soon ? we are stuck with this :( 
I no release is planned yet, could you please tell us how to correct manually ?
Thanks !

**Comment by acasademont** [comment]
Would be better to ping @srgtuszy for that I guess, a release would be much appreciated

**Comment by JaapWeijland** [comment]
We would also appreciate a quick release!

**Comment by jdeibe** [comment]
how do I manually fix this for react-native app using the react-native-ble-plx ? I see some instructions above but not sure how to use them @below thanks!

**Pull request merged**
